#!/usr/bin/env python3
"""Serialize frozen R006 JSON objects into Lean literals.

No mathematical rows, parity equations, or verification results are generated
here. The Lean code recomputes those from factor bits and certificate coordinate
lists. This script is therefore a transparent syntax/transport bridge only.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
IN = ROOT / "formal_inputs"
OUT = ROOT / "R006" / "GeneratedData.lean"


def lean_bool(x: int) -> str:
    assert x in (0, 1)
    return "true" if x else "false"


def factor_expr(data: dict) -> str:
    mats = []
    for key in ("U", "V", "W"):
        rows = []
        for row in data[key]:
            assert len(row) == 16
            rows.append("#[" + ", ".join(lean_bool(int(x)) for x in row) + "]")
        mats.append("#[\n      " + ",\n      ".join(rows) + "\n    ]")
    return "#[\n    " + ",\n    ".join(mats) + "\n  ]"


def coords_expr(coords) -> str:
    for x in coords:
        assert len(x) == 3 and all(0 <= int(v) < 16 for v in x)
    return "#[" + ", ".join(f"c {int(a)} {int(b)} {int(c_)}" for a,b,c_ in coords) + "]"


def edit_certs_expr(items) -> str:
    out=[]
    for item in items:
        q,r,i = map(int, item["edit"][:3])
        assert 0 <= q < 3 and 0 <= r < 47 and 0 <= i < 16
        out.append(f"{{ edit := e {q} {r} {i}, equations := {coords_expr(item['equations'])} }}")
    return "#[\n    " + ",\n    ".join(out) + "\n  ]"


def load(name):
    return json.loads((IN / name).read_text())


def main() -> None:
    alpha = load("f3__data__r47_alphatensor_f2_factors.json")
    flips = load("f3__data__r47_flips_data.json")
    # The mod-4 and F3 factor payloads are independently frozen copies and must agree.
    assert alpha == load("mod4__data__r47_alphatensor_f2_factors.json")
    assert flips == load("mod4__data__r47_flips_data.json")

    am = load("mod4__certificates__alpha_mod4_result_generic.json")
    fm = load("mod4__certificates__flips_mod4_result.json")
    af = load("f3__certificates__alpha_distance1_f3_obstruction.json")
    ff = load("f3__certificates__flips_distance1_f3_obstruction.json")

    text = f'''-- AUTO-GENERATED by formal/generate_lean_data.py from SHA-pinned R006 artifacts.
-- This file contains data only; all mathematical checks are recomputed in Lean.
import Mathlib

namespace R006.GeneratedData

abbrev Coord := Nat × Nat × Nat
abbrev Edit := Nat × Nat × Nat

structure EditCertificate where
  edit : Edit
  equations : Array Coord
  deriving Repr

private def c (a b c : Nat) : Coord := (a, b, c)
private def e (q r i : Nat) : Edit := (q, r, i)

def alphaFactors : Array (Array (Array Bool)) := {factor_expr(alpha)}

def flipsFactors : Array (Array (Array Bool)) := {factor_expr(flips)}

def alphaMod4Certificate : Array Coord := {coords_expr(am['contradiction_certificate']['decoded_equations'])}

def flipsMod4Certificate : Array Coord := {coords_expr(fm['contradiction_certificate']['decoded_equations'])}

def alphaF3BaseCertificate : Array Coord := {coords_expr(af['base_certificate_equations'])}

def flipsF3BaseCertificate : Array Coord := {coords_expr(ff['base_certificate_equations'])}

def alphaF3EditCertificates : Array EditCertificate := {edit_certs_expr(af['edit_certificates'])}

def flipsF3EditCertificates : Array EditCertificate := {edit_certs_expr(ff['edit_certificates'])}

end R006.GeneratedData
'''
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text)} bytes)")

if __name__ == "__main__":
    main()
